# Beehive Sensor Data Anylsis
- Processing the raw bee date to a clean data set for furhter consumption

In [26]:
import pandas as pd
from pymongo import MongoClient
from pymongo.server_api import ServerApi
import streamlit as st
from hampel import hampel
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

In [18]:
uri = st.secrets["mongodb"]["uri"]
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# MongoDB Atlas Connection
db = client["beehive_monitoring"]  # Database name
collection = db["bee_sensor_telemetry"]  # Collection name

Load Data

In [19]:
# Read data from MongoDB into a pandas DataFrame
data = pd.DataFrame(list(collection.find()))
print(data.dtypes)
data

_id             object
beehive_id      object
weight         float64
temperature    float64
humidity       float64
timestamp       object
dtype: object

,_id,beehive_id,weight,temperature,humidity,timestamp
0,679665ae0d8001aa456a10e1,2,24.73,19.9,74.0,2025-01-26 17:41:15
1,679668030d8001aa456a10e2,2,24.74,20.1,75.0,2025-01-26 17:51:15
2,6796697ee0ee352edb1f5f17,2,46.38,19.8,93.0,2020-10-08T17:47:31+02:00
3,6796697ee0ee352edb1f5f18,2,46.43,19.8,93.0,2020-10-08T17:57:35+02:00
4,6796697ee0ee352edb1f5f19,2,46.40,19.8,93.0,2020-10-08T18:07:40+02:00
...,...,...,...,...,...,...
110319,6796697fe0ee352edb210e04,2,24.73,19.9,74.0,2025-01-26 17:41:15
110320,67966a5b0d8001aa456a10e3,2,24.75,20.1,73.0,2025-01-26 18:01:15
110321,67966cb30d8001aa456a10e4,2,24.75,20.1,71.0,2025-01-26 18:11:14
110322,67966f0a0d8001aa456a10e5,2,24.75,20.1,77.0,2025-01-26 18:21:14
110323,679671620d8001aa456a10e6,2,24.75,20.1,78.0,2025-01-26 18:31:13

## Preprocessing

In [21]:
#CASTING
# Convert string column to datetime
data['timestamp'] = pd.to_datetime(data['timestamp'], format='mixed', yearfirst=True, utc=True)
print(data[data['timestamp'].isna()])
data = data[pd.to_numeric(data['temperature'], errors='coerce').notnull()]
data['humidity'] = data['humidity'].astype(float)

# Extract the year and create a new column
data['year'] = data['timestamp'].dt.year
data['month'] = data['timestamp'].dt.month
data['day'] = data['timestamp'].dt.day
# Concatenate 'month' and 'day' into a single column
data['month_day'] = data['timestamp'].dt.strftime('%m-%d')

# Remove rows where 'weight' is equal to "~"
data = data[data['weight'] != "~"]
# Convert 'weight' column to float
data.loc[:, 'weight'] = data['weight'].astype(float)
data = data[data['weight'] >= 0]

C:\Users\timwy\AppData\Local\Temp\ipykernel_30484\1430328253.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['timestamp'] = pd.to_datetime(data['timestamp'], format='mixed', yearfirst=True, utc=True)

Empty DataFrame
Columns: [_id, beehive_id, weight, temperature, humidity, timestamp]
Index: []

## Hampel Filtering

In [23]:
data.set_index('timestamp', inplace=True)
# Apply the Hampel filter
WINDOW_SIZE = 144 # 10 min/datapoint | 6 datapoint/hour | 144 datapoints/day
result = hampel(data['weight'], window_size=WINDOW_SIZE, n_sigma=3.0)

data_weight_filtered = result.filtered_data
outlier_indices = result.outlier_indices
medians = result.medians
mad_values = result.median_absolute_deviations
thresholds = result.thresholds
print(data_weight_filtered)

0        24.730000
1        24.740000
2        46.380001
3        46.430000
4        46.400002
           ...
51262    24.730000
51263    24.750000
51264    24.750000
51265    24.750000
51266    24.750000
Length: 51267, dtype: float32

# Save Silver version (cleaned data set)

In [27]:
fig, axes = plt.subplots(2, 1, figsize=(8, 6))
index_start = 150000

# Plot the original data with estimated standard deviations in the first subplot
axes[0].plot(data['weight'].iloc[index_start:], label='Original Data', color='b')

# Optionally fill the area between the bands (commented out in your code)
# axes[0].fill_between(data['date'].iloc[index_start:], medians + thresholds, medians - thresholds, color='gray', alpha=0.5, label='Median +- Threshold')

axes[0].set_xlabel('Date')
axes[0].set_ylabel('Weight')
axes[0].set_title('Original Data with Bands representing Upper and Lower limits')

# Format the x-axis to display dates nicely
axes[0].xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
axes[0].xaxis.set_major_locator(mdates.AutoDateLocator())

# Rotate the date labels for better readability
plt.setp(axes[0].get_xticklabels(), rotation=45, ha='right')

axes[0].legend()

# Plot the filtered data in the second subplot
axes[1].plot(data_weight_filtered.iloc[index_start:], label='Filtered Data', color='g')
axes[1].set_xlabel('Data Point')
axes[1].set_ylabel('Value')
axes[1].set_title('Filtered Data')
axes[1].legend()

# Adjust spacing between subplots
plt.tight_layout()

# Show the plots
plt.show()

C:\Users\timwy\AppData\Local\Temp\ipykernel_30484\1251895470.py:34: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

add filterd weight data back to original data set and change index

In [28]:
data_weight_filtered.index = data.index
data['weight_cleaned'] = data_weight_filtered

data = data.reset_index()
data

,timestamp,_id,beehive_id,weight,temperature,humidity,year,month,day,month_day,weight_cleaned
0,2025-01-26 17:41:15+00:00,679665ae0d8001aa456a10e1,2,24.73,19.9,74.0,2025,1,26,01-26,24.730000
1,2025-01-26 17:51:15+00:00,679668030d8001aa456a10e2,2,24.74,20.1,75.0,2025,1,26,01-26,24.740000
2,2020-10-08 15:47:31+00:00,6796697ee0ee352edb1f5f17,2,46.38,19.8,93.0,2020,10,8,10-08,46.380001
3,2020-10-08 15:57:35+00:00,6796697ee0ee352edb1f5f18,2,46.43,19.8,93.0,2020,10,8,10-08,46.430000
4,2020-10-08 16:07:40+00:00,6796697ee0ee352edb1f5f19,2,46.40,19.8,93.0,2020,10,8,10-08,46.400002
...,...,...,...,...,...,...,...,...,...,...,...
51262,2025-01-26 17:41:15+00:00,6796697fe0ee352edb210e04,2,24.73,19.9,74.0,2025,1,26,01-26,24.730000
51263,2025-01-26 18:01:15+00:00,67966a5b0d8001aa456a10e3,2,24.75,20.1,73.0,2025,1,26,01-26,24.750000
51264,2025-01-26 18:11:14+00:00,67966cb30d8001aa456a10e4,2,24.75,20.1,71.0,2025,1,26,01-26,24.750000
51265,2025-01-26 18:21:14+00:00,67966f0a0d8001aa456a10e5,2,24.75,20.1,77.0,2025,1,26,01-26,24.750000
51266,2025-01-26 18:31:13+00:00,679671620d8001aa456a10e6,2,24.75,20.1,78.0,2025,1,26,01-26,24.750000

# Aggreation

In [30]:
# Group by year and month, then calculate the average of weight, temperature, and humidity
grouped_data = data.groupby(['year', 'month']).agg({
    'weight_cleaned': 'mean',
    'temperature': 'mean',
    'humidity': 'mean'
}).reset_index()


print(grouped_data)

    year  month  weight_cleaned  temperature   humidity
0   2020     10       42.670467    20.937934  88.403846
1   2020     11       28.175545    18.504772  92.490400
2   2020     12       23.925100    15.139566  91.294690
3   2021      1       21.989067    13.022160  90.010494
4   2021      2       27.962280     6.325112  86.457290
5   2021      5       21.214140    14.261992  79.395551
6   2021      6       24.319473    21.441696  74.753828
7   2021      7       33.264526    28.061766  75.561437
8   2021      8       38.070126    28.696538  83.768546
9   2021      9       38.443844    26.362826  85.916701
10  2022      7       40.042000    28.700000  72.400000
11  2022      8       30.742712    30.149420  82.115483
12  2022      9       46.182747    22.410051  87.755695
13  2022     10       30.441818    15.202815  88.895897
14  2022     11       25.962296     7.750658  88.153369
15  2022     12       28.063236     4.847010  87.391629
16  2023      1       38.880806     5.990113  87.587059
17  2023      2       30.054388     4.770511  87.067511
18  2023      3       20.635723     6.933333  87.471698
19  2024      6        3.680000    52.850000  40.680000
20  2024     10        8.656220    14.450468  81.934673
21  2024     11       43.430206    15.796606  88.610215
22  2025      1       24.970797    17.449336  86.751788

# Save

In [8]:
# # Saving the DataFrame to a CSV file
# data.to_csv('.streamlit/24-09-21_beehive_cleaned.csv', index=False)

In [31]:
# Define the new collection name
new_collection_name = "bee_sensor_telemetry_agg"

# Get the new collection
new_collection = db[new_collection_name]

# Convert the DataFrame to a list of dictionaries
data_dict = grouped_data.to_dict("records")
display(data_dict)

# Insert the cleaned data into the new collection
new_collection.insert_many(data_dict)

print(f"Data successfully saved to the '{new_collection_name}' collection.")

[{'year': 2020,
  'month': 10,
  'weight_cleaned': 42.670467376708984,
  'temperature': 20.937933634992458,
  'humidity': 88.40384615384616},
 {'year': 2020,
  'month': 11,
  'weight_cleaned': 28.17554473876953,
  'temperature': 18.50477235326385,
  'humidity': 92.49040043883709},
 {'year': 2020,
  'month': 12,
  'weight_cleaned': 23.925100326538086,
  'temperature': 15.139566192969333,
  'humidity': 91.29468960359013},
 {'year': 2021,
  'month': 1,
  'weight_cleaned': 21.98906707763672,
  'temperature': 13.022160493827162,
  'humidity': 90.01049382716049},
 {'year': 2021,
  'month': 2,
  'weight_cleaned': 27.9622802734375,
  'temperature': 6.325112395632627,
  'humidity': 86.4572896596018},
 {'year': 2021,
  'month': 5,
  'weight_cleaned': 21.214139938354492,
  'temperature': 14.261992263056092,
  'humidity': 79.39555125725339},
 {'year': 2021,
  'month': 6,
  'weight_cleaned': 24.319473266601562,
  'temperature': 21.441696113074205,
  'humidity': 74.75382803297998},
 {'year': 2021,
  'month': 7,
  'weight_cleaned': 33.2645263671875,
  'temperature': 28.061766319253977,
  'humidity': 75.56143719144268},
 {'year': 2021,
  'month': 8,
  'weight_cleaned': 38.070125579833984,
  'temperature': 28.696538081107814,
  'humidity': 83.76854599406528},
 {'year': 2021,
  'month': 9,
  'weight_cleaned': 38.443843841552734,
  'temperature': 26.36282635723166,
  'humidity': 85.91670120182346},
 {'year': 2022,
  'month': 7,
  'weight_cleaned': 40.04199981689453,
  'temperature': 28.7,
  'humidity': 72.4},
 {'year': 2022,
  'month': 8,
  'weight_cleaned': 30.742712020874023,
  'temperature': 30.14941975658081,
  'humidity': 82.11548259269742},
 {'year': 2022,
  'month': 9,
  'weight_cleaned': 46.18274688720703,
  'temperature': 22.41005125284738,
  'humidity': 87.75569476082005},
 {'year': 2022,
  'month': 10,
  'weight_cleaned': 30.441818237304688,
  'temperature': 15.20281451339437,
  'humidity': 88.89589691420821},
 {'year': 2022,
  'month': 11,
  'weight_cleaned': 25.962295532226562,
  'temperature': 7.750658404337723,
  'humidity': 88.15336948102247},
 {'year': 2022,
  'month': 12,
  'weight_cleaned': 28.063236236572266,
  'temperature': 4.847010463378177,
  'humidity': 87.39162929745889},
 {'year': 2023,
  'month': 1,
  'weight_cleaned': 38.88080596923828,
  'temperature': 5.990112686295892,
  'humidity': 87.58705925118139},
 {'year': 2023,
  'month': 2,
  'weight_cleaned': 30.05438804626465,
  'temperature': 4.77051101734646,
  'humidity': 87.0675105485232},
 {'year': 2023,
  'month': 3,
  'weight_cleaned': 20.635723114013672,
  'temperature': 6.933333333333334,
  'humidity': 87.47169811320755},
 {'year': 2024,
  'month': 6,
  'weight_cleaned': 3.680000066757202,
  'temperature': 52.85,
  'humidity': 40.68},
 {'year': 2024,
  'month': 10,
  'weight_cleaned': 8.656220436096191,
  'temperature': 14.450467719674897,
  'humidity': 81.93467259622757},
 {'year': 2024,
  'month': 11,
  'weight_cleaned': 43.430206298828125,
  'temperature': 15.796606182795697,
  'humidity': 88.61021505376344},
 {'year': 2025,
  'month': 1,
  'weight_cleaned': 24.970796585083008,
  'temperature': 17.449336057201226,
  'humidity': 86.7517875383044}]

Data successfully saved to the 'bee_sensor_telemetry_agg' collection.