# Manual CSV Load into MongoDB

In [42]:
import pandas as pd
from pymongo import MongoClient
from pymongo.server_api import ServerApi
import streamlit as st
from hampel import hampel

Load Data

In [43]:
data = pd.read_csv("./.streamlit/25-01-27 Bienenwaage1.csv")
print(data.dtypes)
data

created_at     object
entry_id        int64
field1         object
field2        float64
field3         object
latitude      float64
longitude     float64
elevation     float64
status        float64
dtype: object

C:\Users\timwy\AppData\Local\Temp\ipykernel_17604\4104083099.py:1: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("./.streamlit/25-01-27 Bienenwaage1.csv")

,created_at,entry_id,field1,field2,field3,latitude,longitude,elevation,status
0,2020-10-14T17:03:37+02:00,1,49.63,78.0,13.1,NaN,NaN,NaN,NaN
1,2020-10-14T17:13:41+02:00,2,49.77,95.0,20.3,NaN,NaN,NaN,NaN
2,2020-10-14T17:23:45+02:00,3,49.79,95.0,23.1,NaN,NaN,NaN,NaN
3,2020-10-14T17:33:49+02:00,4,49.78,86.0,23.4,NaN,NaN,NaN,NaN
4,2020-10-14T17:43:53+02:00,5,49.77,79.0,23.5,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
189685,2025-01-27T17:46:54+01:00,189686,40.64,88.0,10.20,NaN,NaN,NaN,NaN
189686,2025-01-27T17:56:55+01:00,189687,40.63,88.0,10.10,NaN,NaN,NaN,NaN
189687,2025-01-27T18:06:57+01:00,189688,40.63,88.0,10.20,NaN,NaN,NaN,NaN
189688,2025-01-27T18:16:58+01:00,189689,40.63,88.0,10.20,NaN,NaN,NaN,NaN
189689,2025-01-27T18:26:59+01:00,189690,40.64,88.0,10.30,NaN,NaN,NaN,NaN

In [44]:
data.rename(columns={'field4': 'timestamp', 'field1': 'weight', 'field2': 'humidity', 'field3': 'temperature', 'created_at':'timestamp'}, inplace=True)
print(data.dtypes)
data = data[['timestamp', 'weight', 'humidity', 'temperature']]
# data['timestamp'].fillna(data['created_at'], inplace=True)
data.head()
data.tail()

df = data[['timestamp', 'weight', 'humidity', 'temperature']]


display(df)

timestamp       object
entry_id         int64
weight          object
humidity       float64
temperature     object
latitude       float64
longitude      float64
elevation      float64
status         float64
dtype: object

                        timestamp weight  humidity temperature
0       2020-10-14T17:03:37+02:00  49.63      78.0        13.1
1       2020-10-14T17:13:41+02:00  49.77      95.0        20.3
2       2020-10-14T17:23:45+02:00  49.79      95.0        23.1
3       2020-10-14T17:33:49+02:00  49.78      86.0        23.4
4       2020-10-14T17:43:53+02:00  49.77      79.0        23.5
...                           ...    ...       ...         ...
189685  2025-01-27T17:46:54+01:00  40.64      88.0       10.20
189686  2025-01-27T17:56:55+01:00  40.63      88.0       10.10
189687  2025-01-27T18:06:57+01:00  40.63      88.0       10.20
189688  2025-01-27T18:16:58+01:00  40.63      88.0       10.20
189689  2025-01-27T18:26:59+01:00  40.64      88.0       10.30

[189690 rows x 4 columns]

## cleaning

In [49]:
data['timestamp'] = pd.to_datetime(data['timestamp'], format='mixed', yearfirst=True, utc=True)
print(data[data['timestamp'].isna()])
# Remove rows where 'weight' is equal to "~"
data = data[data['weight'] != "~"]
# Convert 'weight' column to float
data.loc[:, 'weight'] = data['weight'].astype(float)
data = data[data['weight'] >= 0]

Empty DataFrame
Columns: [timestamp, weight, humidity, temperature]
Index: []

C:\Users\timwy\AppData\Local\Temp\ipykernel_17604\663850876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['timestamp'] = pd.to_datetime(data['timestamp'], format='mixed', yearfirst=True, utc=True)

In [50]:
data['temperature'] = pd.to_numeric(data['temperature'], errors='coerce')
display(data[data['temperature'].isna()])

                       timestamp  weight  humidity  temperature
5118   2020-11-21 06:48:53+00:00    0.36       NaN          NaN
49848  2021-10-18 21:04:51+00:00   35.79       NaN          NaN
76539  2022-05-19 16:41:10+00:00  107.78       NaN          NaN
113969 2023-05-20 20:23:20+00:00   24.59       NaN          NaN
113970 2023-05-20 20:33:24+00:00   24.59       NaN          NaN
...                          ...     ...       ...          ...
161585 2024-06-28 14:37:48+00:00   43.12       NaN          NaN
161586 2024-06-28 14:47:49+00:00   43.11       NaN          NaN
161587 2024-06-28 14:57:51+00:00    43.1       NaN          NaN
161588 2024-06-28 15:07:52+00:00   43.08       NaN          NaN
163084 2024-07-09 09:53:55+00:00    36.0       NaN          NaN

[4624 rows x 4 columns]

In [51]:

data['humidity'] = data['humidity'].astype(float)
data['temperature'] = data['temperature'].astype(float)

In [52]:
data.set_index('timestamp', inplace=True)
# Apply the Hampel filter
WINDOW_SIZE = 144 # 10 min/datapoint | 6 datapoint/hour | 144 datapoints/day
result = hampel(data['weight'], window_size=WINDOW_SIZE, n_sigma=3.0)

data_weight_filtered = result.filtered_data
outlier_indices = result.outlier_indices
medians = result.medians
mad_values = result.median_absolute_deviations
thresholds = result.thresholds
print(data_weight_filtered)

0         49.630001
1         49.770000
2         49.790001
3         49.779999
4         49.770000
            ...
187694    40.639999
187695    40.630001
187696    40.630001
187697    40.630001
187698    40.639999
Length: 187699, dtype: float32

In [53]:
data_weight_filtered.index = data.index
data['weight'] = data_weight_filtered

data = data.reset_index()
#create a column beehive_id with the value 2
data['beehive_id'] = "1"
data['timestamp'] = data['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')
data

                  timestamp     weight  humidity  temperature beehive_id
0       2020-10-14 15:03:37  49.630001      78.0         13.1          1
1       2020-10-14 15:13:41  49.770000      95.0         20.3          1
2       2020-10-14 15:23:45  49.790001      95.0         23.1          1
3       2020-10-14 15:33:49  49.779999      86.0         23.4          1
4       2020-10-14 15:43:53  49.770000      79.0         23.5          1
...                     ...        ...       ...          ...        ...
187694  2025-01-27 16:46:54  40.639999      88.0         10.2          1
187695  2025-01-27 16:56:55  40.630001      88.0         10.1          1
187696  2025-01-27 17:06:57  40.630001      88.0         10.2          1
187697  2025-01-27 17:16:58  40.630001      88.0         10.2          1
187698  2025-01-27 17:26:59  40.639999      88.0         10.3          1

[187699 rows x 5 columns]

In [54]:
uri = st.secrets["mongodb"]["uri"]
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# MongoDB Atlas Connection
db = client["beehive_monitoring"]  # Database name
collection = db["bee_sensor_telemetry"]  # Collection name

def insert_data_to_mongodb(beehive_id, weight, temperature, humidity, timestamp):
    """
    Inserts the received data into MongoDB Atlas.
    """
    data = {
        "beehive_id": beehive_id,
        "weight": float(weight),
        "temperature": float(temperature) if temperature != "nan" else None,
        "humidity": float(humidity) if humidity != "nan" else None,
        "timestamp": timestamp
    }
    
    try:
        result = collection.insert_one(data)
        print(f"Data inserted into MongoDB with ID: {result.inserted_id}")
    except Exception as e:
        print(f"Error inserting data to MongoDB: {e}")

In [27]:
# Example data for testing
beehive_id = "hive_01"
weight = 12.5
temperature = 35.2
humidity = 60.5
timestamp = "2023-10-01T12:00:00Z"

# Insert the example data into MongoDB
# insert_data_to_mongodb(beehive_id, weight, temperature, humidity, timestamp)

In [28]:
records = df.to_dict(orient='records')
display(records)

[{'timestamp': '2020-10-08T17:47:31+02:00',
  'weight': 46.38,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T17:57:35+02:00',
  'weight': 46.43,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T18:07:40+02:00',
  'weight': 46.4,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T18:17:44+02:00',
  'weight': 46.42,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T18:27:48+02:00',
  'weight': 46.36,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T18:37:53+02:00',
  'weight': 46.37,
  'humidity': 93.0,
  'temperature': 20.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T18:47:57+02:00',
  'weight': 46.34,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T18:58:01+02:00',
  'weight': 46.36,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T19:08:06+02:00',
  'weight': 46.48,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T19:18:10+02:00',
  'weight': 46.39,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T19:28:14+02:00',
  'weight': 46.42,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T19:38:19+02:00',
  'weight': 46.42,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T19:48:23+02:00',
  'weight': 46.41,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T19:58:28+02:00',
  'weight': 46.41,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T20:08:32+02:00',
  'weight': 46.4,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T20:18:36+02:00',
  'weight': 46.41,
  'humidity': 93.0,
  'temperature': 20.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T20:28:41+02:00',
  'weight': 46.42,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T20:38:45+02:00',
  'weight': 46.44,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T20:48:49+02:00',
  'weight': 46.4,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T20:58:54+02:00',
  'weight': 46.46,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T21:08:58+02:00',
  'weight': 46.37,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T21:19:03+02:00',
  'weight': 46.4,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T21:29:07+02:00',
  'weight': 46.44,
  'humidity': 93.0,
  'temperature': 20.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T21:39:11+02:00',
  'weight': 46.45,
  'humidity': 93.0,
  'temperature': 20.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T21:49:16+02:00',
  'weight': 46.4,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T21:59:20+02:00',
  'weight': 46.42,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T22:09:25+02:00',
  'weight': 46.38,
  'humidity': 93.0,
  'temperature': 20.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T22:19:29+02:00',
  'weight': 46.43,
  'humidity': 93.0,
  'temperature': 20.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T22:29:34+02:00',
  'weight': 46.44,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T22:39:38+02:00',
  'weight': 46.43,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T22:49:42+02:00',
  'weight': 46.41,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T22:59:47+02:00',
  'weight': 46.42,
  'humidity': 93.0,
  'temperature': 20.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T23:09:51+02:00',
  'weight': 46.33,
  'humidity': 93.0,
  'temperature': 20.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T23:19:55+02:00',
  'weight': 46.5,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T23:30:00+02:00',
  'weight': 46.44,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T23:40:04+02:00',
  'weight': 46.52,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-08T23:50:08+02:00',
  'weight': 46.51,
  'humidity': 93.0,
  'temperature': 20.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T00:00:13+02:00',
  'weight': 46.52,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T00:10:17+02:00',
  'weight': 46.51,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T00:20:22+02:00',
  'weight': 46.48,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T00:30:26+02:00',
  'weight': 46.54,
  'humidity': 93.0,
  'temperature': 20.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T00:40:30+02:00',
  'weight': 46.49,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T00:50:35+02:00',
  'weight': 46.51,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T01:00:39+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T01:10:44+02:00',
  'weight': 46.61,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T01:20:48+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T01:30:52+02:00',
  'weight': 46.62,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T01:40:57+02:00',
  'weight': 46.61,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T01:51:01+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 20.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T02:01:05+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T02:11:10+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T02:21:14+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T02:31:18+02:00',
  'weight': 46.62,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T02:41:23+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T02:51:27+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T03:01:32+02:00',
  'weight': 46.65,
  'humidity': 93.0,
  'temperature': 19.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T03:11:39+02:00',
  'weight': 46.66,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T03:21:40+02:00',
  'weight': 46.65,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T03:31:45+02:00',
  'weight': 46.65,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T03:41:49+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T03:51:53+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T04:01:58+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T04:12:02+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T04:22:06+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T04:32:10+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T04:42:15+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T04:52:19+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T05:02:24+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T05:12:28+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T05:22:32+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T05:32:37+02:00',
  'weight': 46.65,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T05:42:41+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T05:52:46+02:00',
  'weight': 46.65,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T06:02:50+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T06:12:54+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T06:22:59+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T06:33:03+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T06:43:07+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T06:53:12+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T07:03:16+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T07:13:20+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T07:23:25+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T07:33:29+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T07:43:33+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T07:53:38+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T08:03:42+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T08:13:47+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T08:23:51+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T08:33:55+02:00',
  'weight': 46.61,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T08:44:00+02:00',
  'weight': 46.63,
  'humidity': 93.0,
  'temperature': 19.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T08:54:04+02:00',
  'weight': 46.62,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T09:14:13+02:00',
  'weight': 46.64,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T09:24:17+02:00',
  'weight': 46.62,
  'humidity': 93.0,
  'temperature': 19.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T09:34:21+02:00',
  'weight': 46.62,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T09:44:26+02:00',
  'weight': 46.62,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T09:54:30+02:00',
  'weight': 46.6,
  'humidity': 93.0,
  'temperature': 19.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T10:04:35+02:00',
  'weight': 46.6,
  'humidity': 93.0,
  'temperature': 19.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T10:14:39+02:00',
  'weight': 46.59,
  'humidity': 93.0,
  'temperature': 19.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T10:24:43+02:00',
  'weight': 46.55,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T10:34:48+02:00',
  'weight': 46.59,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T10:44:52+02:00',
  'weight': 46.6,
  'humidity': 93.0,
  'temperature': 20.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T10:54:57+02:00',
  'weight': 46.58,
  'humidity': 93.0,
  'temperature': 19.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T11:05:01+02:00',
  'weight': 46.57,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T11:15:06+02:00',
  'weight': 46.57,
  'humidity': 93.0,
  'temperature': 20.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T11:25:10+02:00',
  'weight': 46.56,
  'humidity': 93.0,
  'temperature': 20.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T11:35:14+02:00',
  'weight': 46.53,
  'humidity': 93.0,
  'temperature': 20.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T11:45:18+02:00',
  'weight': 46.55,
  'humidity': 93.0,
  'temperature': 20.2,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T11:55:23+02:00',
  'weight': 46.56,
  'humidity': 93.0,
  'temperature': 20.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T12:05:27+02:00',
  'weight': 46.56,
  'humidity': 93.0,
  'temperature': 20.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T12:15:32+02:00',
  'weight': 46.55,
  'humidity': 93.0,
  'temperature': 20.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T12:25:36+02:00',
  'weight': 46.56,
  'humidity': 94.0,
  'temperature': 21.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T12:35:40+02:00',
  'weight': 46.55,
  'humidity': 94.0,
  'temperature': 21.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T12:45:44+02:00',
  'weight': 46.51,
  'humidity': 94.0,
  'temperature': 21.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T12:55:49+02:00',
  'weight': 46.46,
  'humidity': 94.0,
  'temperature': 21.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T13:05:53+02:00',
  'weight': 46.47,
  'humidity': 95.0,
  'temperature': 22.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T13:15:58+02:00',
  'weight': 46.46,
  'humidity': 95.0,
  'temperature': 22.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T13:26:02+02:00',
  'weight': 46.47,
  'humidity': 95.0,
  'temperature': 23.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T13:36:06+02:00',
  'weight': 46.43,
  'humidity': 95.0,
  'temperature': 24.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T13:46:11+02:00',
  'weight': 46.39,
  'humidity': 95.0,
  'temperature': 24.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T13:56:28+02:00',
  'weight': 43.15,
  'humidity': 95.0,
  'temperature': 25.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T14:06:32+02:00',
  'weight': 43.28,
  'humidity': 91.0,
  'temperature': 22.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T14:16:37+02:00',
  'weight': 43.28,
  'humidity': 94.0,
  'temperature': 32.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T14:26:41+02:00',
  'weight': 43.26,
  'humidity': 85.0,
  'temperature': 32.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T14:36:45+02:00',
  'weight': 43.28,
  'humidity': 84.0,
  'temperature': 33.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T14:46:50+02:00',
  'weight': 43.24,
  'humidity': 83.0,
  'temperature': 32.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T14:56:54+02:00',
  'weight': 43.25,
  'humidity': 79.0,
  'temperature': 33.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T15:06:59+02:00',
  'weight': 43.26,
  'humidity': 82.0,
  'temperature': 33.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T15:17:03+02:00',
  'weight': 43.27,
  'humidity': 75.0,
  'temperature': 33.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T15:27:08+02:00',
  'weight': 43.25,
  'humidity': 77.0,
  'temperature': 33.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T15:37:12+02:00',
  'weight': 43.25,
  'humidity': 81.0,
  'temperature': 33.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T15:47:17+02:00',
  'weight': 43.24,
  'humidity': 80.0,
  'temperature': 34.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T15:57:21+02:00',
  'weight': 43.22,
  'humidity': 80.0,
  'temperature': 34.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T16:07:25+02:00',
  'weight': 43.22,
  'humidity': 78.0,
  'temperature': 34.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T16:17:30+02:00',
  'weight': 43.23,
  'humidity': 74.0,
  'temperature': 33.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T16:27:34+02:00',
  'weight': 43.29,
  'humidity': 70.0,
  'temperature': 33.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T16:37:39+02:00',
  'weight': 43.25,
  'humidity': 73.0,
  'temperature': 33.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T16:47:43+02:00',
  'weight': 43.26,
  'humidity': 70.0,
  'temperature': 33.6,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T16:57:48+02:00',
  'weight': 43.29,
  'humidity': 71.0,
  'temperature': 33.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T17:07:52+02:00',
  'weight': 43.27,
  'humidity': 70.0,
  'temperature': 33.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T17:17:56+02:00',
  'weight': 43.25,
  'humidity': 71.0,
  'temperature': 33.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T17:28:01+02:00',
  'weight': 43.22,
  'humidity': 73.0,
  'temperature': 32.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T17:38:05+02:00',
  'weight': 43.21,
  'humidity': 68.0,
  'temperature': 32.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T17:48:10+02:00',
  'weight': 43.37,
  'humidity': 76.0,
  'temperature': 33.0,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T17:58:14+02:00',
  'weight': 43.39,
  'humidity': 77.0,
  'temperature': 32.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T18:08:18+02:00',
  'weight': 43.39,
  'humidity': 83.0,
  'temperature': 32.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T18:18:23+02:00',
  'weight': 43.4,
  'humidity': 74.0,
  'temperature': 32.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T18:28:27+02:00',
  'weight': 43.4,
  'humidity': 69.0,
  'temperature': 32.4,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T18:38:32+02:00',
  'weight': 43.4,
  'humidity': 67.0,
  'temperature': 32.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T18:48:36+02:00',
  'weight': 43.38,
  'humidity': 70.0,
  'temperature': 32.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T18:58:40+02:00',
  'weight': 43.43,
  'humidity': 68.0,
  'temperature': 31.9,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T19:08:45+02:00',
  'weight': 43.43,
  'humidity': 69.0,
  'temperature': 31.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T19:18:49+02:00',
  'weight': 43.43,
  'humidity': 68.0,
  'temperature': 31.7,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T19:28:54+02:00',
  'weight': 43.42,
  'humidity': 67.0,
  'temperature': 31.5,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T19:38:58+02:00',
  'weight': 43.41,
  'humidity': 75.0,
  'temperature': 31.1,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T19:49:02+02:00',
  'weight': 43.41,
  'humidity': 71.0,
  'temperature': 30.8,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T19:59:07+02:00',
  'weight': 43.45,
  'humidity': 70.0,
  'temperature': 30.3,
  'beehive_id': '2'},
 {'timestamp': '2020-10-09T20:09:11+02:00',

In [56]:
def load_dataframe_to_mongodb(df, collection):
    """
    Loads data from a pandas DataFrame into a MongoDB collection.
    
    Parameters:
    df (pandas.DataFrame): The DataFrame containing the data to be loaded.
    collection (pymongo.collection.Collection): The MongoDB collection where the data will be inserted.
    """
    records = df.to_dict(orient='records')
    try:
        result = collection.insert_many(records)
        print(f"Inserted {len(result.inserted_ids)} records into MongoDB.")
    except Exception as e:
        print(f"Error inserting data to MongoDB: {e}")

# Load the data from the DataFrame into MongoDB
load_dataframe_to_mongodb(data, collection)

Inserted 187699 records into MongoDB.

In [55]:
result = collection.delete_many({"beehive_id": "1"})
print(f"Deleted {result.deleted_count} documents.")

Deleted 183075 documents.